(() => {
  const supportedLocales = [
    "ja",
    "en",
    "zh-Hans",
    "zh-Hant",
    "es",
    "hi",
    "pt",
    "fr",
    "it"
  ];

  const english = {
    "meta.description": "Turn rough phonetic input and typos into natural writing with AI, then insert the selected result into the app you were already using.",
    "document.title": "Nospace — Write at the speed of thought.",
    "skip.main": "Skip to main content",
    "brand.homeLabel": "Go to the Nospace homepage",
    "nav.label": "Main navigation",
    "nav.flow": "How it works",
    "nav.cost": "Cost",
    "nav.privacy": "Data and permissions",
    "nav.download": "Download",
    "hero.title": "<span class=\"hero__headline-line hero__headline-line--ink\">Write at the speed</span><br><em>of thought.</em>",
    "hero.lede": "Type freely, mistakes included, and let Nospace turn the rough draft into something natural.",
    "hero.privacyLink": "See how data is handled",
    "hero.note": "Your text goes to the API you choose to generate candidates. The API key stays in the macOS Keychain.",
    "hero.shortcutLabel": "Open the input panel with Shift Space",
    "hero.openWith": "OPEN WITH",
    "hero.visualAria": "Nospace demo: type phonetic text, review natural candidates, and insert the selected result",
    "hero.demoLanguage": "English",
    "hero.demoMeta": "PRODUCT DEMO",
    "hero.demoTogglePause": "Pause the demo video",
    "hero.demoTogglePlay": "Play the demo video",
    "hero.demoPause": "PAUSE",
    "hero.demoPlay": "PLAY",
    "hero.demoEditorTitle": "Nospace",
    "hero.demoEditorSubtitle": "Edited",
    "hero.demoEditorMode": "Plain Text",
    "hero.demoEditorLine": "1",
    "hero.demoEditorStatus": "Line: 1  Character: 0  Position: 0",
    "hero.demoPanelSettings": "Demo settings",
    "hero.demoPanelInputPlaceholder": "Type in phonetic text…",
    "hero.demoPanelLanguageEnglish": "English",
    "hero.demoPanelLanguageTarget": "English",
    "hero.demoPanelConvert": "Generate",
    "hero.demoPanelShortcuts": "↵ New line",
    "hero.demoPanelLoading": "Reconstructing natural text",
    "hero.demoPanelCancel": "Cancel",
    "hero.demoPanelCandidateCount": "{count} candidates",
    "hero.demoPanelCandidateCountOne": "{count} candidate",
    "hero.demoPanelAdjust": "Adjust",
    "hero.demoPanelRegenerate": "Regenerate",
    "hero.demoPanelAddDictionary": "Add to dictionary",
    "hero.demoPanelEdit": "Edit　↪",
    "hero.demoPanelTranslate": "Translate ⌘T",
    "hero.demoPanelSelect": "↑↓ Select",
    "hero.demoPanelInsert": "↵ Insert",
    "hero.demoPanelClose": "esc Close",
    "hero.sr": "A silent product demo shows phonetic input becoming natural candidates and the selected result returning to the focused app.",
    "hero.visualFootInput": "Type the rough version",
    "hero.visualFootSelect": "Choose a candidate",
    "eyebrow.howItFlows": "HOW IT FLOWS",
    "eyebrow.plainOnPurpose": "PLAIN, ON PURPOSE",
    "eyebrow.startTyping": "START TYPING",
    "eyebrow.websiteAnalytics": "WEBSITE ANALYTICS",
    "demo.input": "INPUT",
    "demo.rawInput": "withnospaceeventyposyourideasbecomenaturaltext",
    "demo.resultOne": "With Nospace, even typos turn your ideas into natural sentences.",
    "demo.resultTwo": "With Nospace, typos can become natural writing in seconds.",
    "demo.resultThree": "Nospace turns rough thoughts into clear, natural text.",
    "demo.resultFour": "Even imperfect input can become a polished sentence.",
    "demo.resultFive": "With Nospace, rough input becomes a sentence that reads naturally.",
    "demo.resultSix": "Nospace reshapes quick thoughts into writing you can use.",
    "demo.resultSeven": "A few typos are enough to start; Nospace handles the rest.",
    "demo.resultEight": "Type the idea first, then let Nospace make it sound natural.",
    "demo.editorText": "With Nospace, even typos turn your ideas into natural sentences.",
    "demo.editorStats": "Line: 1  Character: 71  Position: 71",
    "demo.select": "↑↓ Select",
    "demo.insert": "↵ Insert",
    "demo.close": "esc Close",
    "process.title": "Write at the,<br><span>speed of thought.</span>",
    "process.lede": "Type. Choose a candidate. Your sentence returns to the place where you started. No extra window to navigate.",
    "process.input.label": "INPUT",
    "process.input.title": "Type the thought,<br>as it comes.",
    "process.input.text": "Typos are fine. Nospace reads the context and shapes it into natural candidates.",
    "process.input.example": "withnospaceeventyposyourideasbecomenaturaltext",
    "process.reconstruct.label": "RECONSTRUCT",
    "process.reconstruct.title": "AI creates five<br>natural options.",
    "process.reconstruct.text": "Candidates follow the context, so you spend less time hunting for the right conversion.",
    "process.reconstruct.example": "With Nospace, even typos turn your ideas into natural sentences.",
    "process.insert.label": "INSERT",
    "process.insert.title": "Put the sentence<br>back in your app.",
    "process.insert.text": "Call it with a shortcut, choose a result, and return to the focus position you left.",
    "process.insert.app": "Notes",
    "process.insert.example": "With Nospace, even typos turn your ideas into natural sentences.",
    "pricing.eyebrow": "COST / PER MANUSCRIPT",
    "pricing.title": "Five dollars,<br><span>about 10,000 pages.</span>",
    "pricing.lede": "Nospace itself has no usage fee. This estimate uses a measured long-form generation to show what five dollars can cover.",
    "pricing.callout.title": "This is a measured estimate.",
    "pricing.callout.text": "Actual charges change with model prices, caching, and contract terms.",
    "pricing.ledger.unit": "LONG GENERATION / MEASURED",
    "pricing.ledger.estimate": "ESTIMATE / USD",
    "pricing.measure.title": "One manuscript page",
    "pricing.measure.text": "1,238 Japanese characters<br>OUTPUT / 400 chars",
    "pricing.model.label": "MODEL",
    "pricing.model.detail": "system prompt included",
    "pricing.provider.meta": "measured response / one call",
    "pricing.provider.estimate": "estimated per call",
    "pricing.rate.input": "INPUT",
    "pricing.rate.cachedInput": "CACHED INPUT",
    "pricing.rate.unusedCachedInput": "0 tok × $0.02 / M",
    "pricing.rate.cacheWrite": "CACHE WRITE",
    "pricing.rate.output": "OUTPUT",
    "pricing.provider.link": "View official pricing",
    "pricing.provider.linkLabel": "View official GPT-5.6 Luna pricing in a new tab",
    "pricing.assumptions.label": "MEASUREMENT",
    "pricing.assumptions.text": "We measured a Responses API request with 3,981 characters of system instructions: 1,156 input tokens, 986 output tokens, and 1,238 output characters. At 400 characters per manuscript page, one call is about 3.1 pages and five dollars is about 3,400 calls or 10,000 pages.",
    "pricing.priceNote.label": "PRICE NOTE",
    "pricing.priceNote.text": "Using short-context rates (input $0.20 / M, cached input $0.02 / M, cache write $0.25 / M, output $1.20 / M): 3 × $0.20 / M + 1,153 × $0.25 / M + 986 × $1.20 / M = $0.00147205.",
    "pricing.longContext.label": "PRICE CHANGES",
    "pricing.longContext.text": "Long-context rates may differ. Model prices, discounts, cache handling, and contract terms can change, so check official pricing and your usage for the actual charge.",
    "privacy.title": "Nospace does not<br><span>keep your data.</span>",
    "privacy.lede": "Nospace talks directly to the API you choose. There is no Nospace relay server.",
    "privacy.card.label": "API DESTINATION",
    "privacy.card.title": "Your text goes<br><strong>to your chosen API.</strong>",
    "privacy.card.text": "Nospace uses the OpenAI API or OpenRouter API directly. Your input and reconstruction instructions go to the selected API, not to a Nospace-owned server or another destination.",
    "privacy.card.destination": "Destination",
    "privacy.card.request": "API request",
    "privacy.card.tag": "No Nospace relay server",
    "privacy.footnotes.keyTitle": "API key",
    "privacy.footnotes.keyText": "Stored in the macOS Keychain.",
    "privacy.footnotes.permissionTitle": "Without permission",
    "privacy.footnotes.permissionText": "Paste the selected result manually from the clipboard.",
    "privacy.footnotes.storageTitle": "App storage",
    "privacy.footnotes.storageText": "Input and candidates are not saved to disk.",
    "privacy.analytics.title": "Website analytics",
    "privacy.analytics.text": "This website uses Google Analytics. If you agree, cookies help analyze visits. If you decline, limited cookie-free information is still sent to Google.",
    "privacy.analytics.link": "How Google uses information",
    "privacy.analytics.linkLabel": "See how Google uses information in a new tab",
    "privacy.analytics.privacyLink": "Google Privacy Policy",
    "privacy.analytics.privacyLinkLabel": "See Google's Privacy Policy in a new tab",
    "consent.title": "Analytics settings",
    "consent.label": "ANALYTICS CHOICE",
    "consent.text": "If you agree, Google Analytics uses cookies to analyze visits. If you decline, limited cookie-free information is still sent to Google. You can change this choice later.",
    "consent.details": "See how data is handled",
    "consent.deny": "Decline",
    "consent.grant": "Agree",
    "consent.settings": "Cookie settings",
    "download.title": "Write the next line<br><span>right away.</span>",
    "download.lede": "macOS 14 or later. Start in a moment.",
    "download.linkLabel": "Download Nospace in a new tab",
    "download.socialLabel": "LATEST UPDATES",
    "download.socialText": "Follow along for releases and new ways to use Nospace.",
    "download.socialLink": "Follow @nospace_app",
    "download.socialAria": "Follow the official Nospace X account in a new tab",
    "footer.tagline": "Write at the speed of thought.",
    "footer.xAria": "Open the official Nospace X account in a new tab"
  };

  const locale = (values) => ({ ...english, ...values });

  const translations = {
    en: english,
    ja: locale({
      "meta.description": "打ち間違いや崩れたローマ字でも、AIで自然な日本語に。選んだ候補をそのまま、いま使っているアプリへ挿入できます。",
      "document.title": "Nospace — もう、スペースキーで変換しない。",
      "skip.main": "本文へスキップ",
      "brand.homeLabel": "Nospaceのトップへ",
      "nav.label": "メインナビゲーション",
      "nav.flow": "しくみ",
      "nav.cost": "料金",
      "nav.privacy": "データと権限",
      "nav.download": "ダウンロード",
      "hero.title": "<span class=\"hero__headline-line hero__headline-line--ink\">もう、スペースキーで</span><br><em>変換しない。</em>",
      "hero.lede": "打ち間違いを気にせずに、ざっと入力するだけで、いい感じに変換できます。",
      "hero.privacyLink": "データの扱いを見る",
      "hero.note": "入力文は候補生成のために、選んだAPIへ。APIキーはmacOSのキーチェーンに保存。",
      "hero.shortcutLabel": "Shift Space で入力パネルを開く",
      "hero.openWith": "OPEN WITH",
      "hero.visualAria": "Nospaceのデモ。ローマ字を入力し、自然な候補を選んで、結果を元のアプリへ挿入します。",
      "hero.demoLanguage": "日本語",
      "hero.demoMeta": "PRODUCT DEMO",
      "hero.demoTogglePause": "デモ動画を一時停止",
      "hero.demoTogglePlay": "デモ動画を再生",
      "hero.demoPause": "一時停止",
      "hero.demoPlay": "再生",
      "hero.demoEditorTitle": "Nospace",
      "hero.demoEditorSubtitle": "編集済み",
      "hero.demoEditorMode": "Plain Text",
      "hero.demoEditorLine": "1",
      "hero.demoEditorStatus": "行: 1　文字: 0　位置: 0",
      "hero.demoPanelSettings": "デモ設定",
      "hero.demoPanelInputPlaceholder": "ローマ字で入力…",
      "hero.demoPanelLanguageEnglish": "英語",
      "hero.demoPanelLanguageTarget": "日本語",
      "hero.demoPanelConvert": "変換",
      "hero.demoPanelShortcuts": "↵ 改行",
      "hero.demoPanelLoading": "自然な日本語に変換しています",
      "hero.demoPanelCancel": "キャンセル",
      "hero.demoPanelCandidateCount": "{count} 件の候補",
      "hero.demoPanelCandidateCountOne": "{count} 件の候補",
      "hero.demoPanelAdjust": "調整",
      "hero.demoPanelRegenerate": "再生成",
      "hero.demoPanelAddDictionary": "単語を登録",
      "hero.demoPanelEdit": "編集　↪",
      "hero.demoPanelTranslate": "翻訳　⌘T",
      "hero.demoPanelSelect": "↑↓ 選択",
      "hero.demoPanelInsert": "↵ 挿入",
      "hero.demoPanelClose": "esc 閉じる",
      "hero.sr": "音声のないデモで、ローマ字入力から自然な候補を表示し、選んだ結果を元のアプリへ戻す流れを確認できます。",
      "hero.visualFootInput": "打ち間違いのまま入力",
      "hero.visualFootSelect": "候補を選ぶだけ",
      "eyebrow.howItFlows": "HOW IT FLOWS",
      "eyebrow.plainOnPurpose": "PLAIN, ON PURPOSE",
      "eyebrow.startTyping": "START TYPING",
      "eyebrow.websiteAnalytics": "WEBSITE ANALYTICS",
      "demo.input": "INPUT",
      "demo.rawInput": "nospacenara,utimatigeegaattemo,omoituitakotobawosubayakusizennnabunnsyounikaetekuremasu",
      "demo.resultOne": "Nospaceなら、打ち間違いがあっても、思いついた言葉を素早く自然な文章に変えてくれます。",
      "demo.resultTwo": "Nospaceなら、打ち間違いがあっても、思い付いた言葉を素早く自然な文章に変えてくれます。",
      "demo.resultThree": "Nospaceなら、誤字があっても、思いついた言葉を素早く自然な文章に変えてくれます。",
      "demo.resultFour": "Nospaceなら、打ち間違いがあっても、思いついたことを素早く自然な文章に変えてくれます。",
      "demo.resultFive": "Nospaceなら、少し崩れた入力でも、伝えたいことを自然な文章にできます。",
      "demo.resultSix": "Nospaceなら、急いで入力した言葉も、読みやすい文章に整えられます。",
      "demo.resultSeven": "Nospaceなら、考えたことをそのまま入力して、自然な文に仕上げられます。",
      "demo.resultEight": "Nospaceなら、多少の打ち間違いがあっても、文章の流れを保てます。",
      "demo.editorText": "Nospaceなら、打ち間違いがあっても、思いついた言葉を素早く自然な文章に変えてくれます。",
      "demo.editorStats": "行: 1　文字: 46　位置: 46",
      "demo.select": "↑↓ 選択",
      "demo.insert": "↵ 挿入",
      "demo.close": "esc 閉じる",
      "process.title": "入力を、<br><span>考える速さに。</span>",
      "process.lede": "キーを打つ。候補を選ぶ。文章が、いまの場所に戻る。余計な画面を行き来しないための入力パネルです。",
      "process.input.label": "INPUT",
      "process.input.title": "思いついたまま、<br>ローマ字で。",
      "process.input.text": "打ち間違えがあっても大丈夫。AIが文脈を見て自然な候補に整えます。",
      "process.input.example": "nospacenara,utimatigeegaattemo,omoituitakotobawosubayakusizennnabunnsyounikaetekuremasu",
      "process.reconstruct.label": "RECONSTRUCT",
      "process.reconstruct.title": "AIが自然な候補を、<br>5つ生成。",
      "process.reconstruct.text": "文脈に合わせた候補を並べるから、スペースキーを何度も打って変換の正解を探す時間が短くなります。",
      "process.reconstruct.example": "Nospaceなら、打ち間違いがあっても、思いついた言葉を素早く自然な文章に変えてくれます。",
      "process.insert.label": "INSERT",
      "process.insert.title": "選んだ文章を、<br>元のアプリへ。",
      "process.insert.text": "ショートカットで呼び出して、選択。テキストは元のフォーカス位置に戻ります。",
      "process.insert.app": "メモ",
      "process.insert.example": "Nospaceなら、打ち間違いがあっても、思いついた言葉を素早く自然な文章に変えてくれます。",
      "pricing.eyebrow": "COST / PER MANUSCRIPT",
      "pricing.title": "5ドルで、<br><span>原稿用紙約1万枚分。</span>",
      "pricing.lede": "Nospace自体の利用料はありません。実測した長文生成をもとに、5ドル分の目安を表示しています。",
      "pricing.callout.title": "これは実測ベースの目安です。",
      "pricing.callout.text": "モデルの価格・キャッシュ・契約条件が変わると、実際の請求額も変わります。",
      "pricing.ledger.unit": "LONG GENERATION / MEASURED",
      "pricing.ledger.estimate": "ESTIMATE / USD",
      "pricing.measure.title": "原稿用紙1枚分",
      "pricing.measure.text": "日本語1,238字<br>OUTPUT / 400字",
      "pricing.model.label": "MODEL",
      "pricing.model.detail": "システムプロンプト込み",
      "pricing.provider.meta": "実測レスポンス / 1回",
      "pricing.provider.estimate": "1回あたりの目安",
      "pricing.rate.input": "INPUT",
      "pricing.rate.cachedInput": "CACHED INPUT",
      "pricing.rate.unusedCachedInput": "0 tok × $0.02 / M",
      "pricing.rate.cacheWrite": "CACHE WRITE",
      "pricing.rate.output": "OUTPUT",
      "pricing.provider.link": "公式料金を見る",
      "pricing.provider.linkLabel": "GPT-5.6 Lunaの公式料金を見る（新しいタブ）",
      "pricing.assumptions.label": "MEASUREMENT",
      "pricing.assumptions.text": "システム指示3,981文字を含むResponses APIのリクエストを実測しました。入力1,156 / 出力986 tokens、出力1,238文字でした。原稿用紙1枚=400字として、1回=約3.1枚、5ドル=約3,400回=約1万枚と計算しています。",
      "pricing.priceNote.label": "PRICE NOTE",
      "pricing.priceNote.text": "短文脈料金（入力 $0.20 / M、cached input $0.02 / M、cache write $0.25 / M、出力 $1.20 / M）で、3 × $0.20 / M + 1,153 × $0.25 / M + 986 × $1.20 / M = $0.00147205 と計算しています。",
      "pricing.longContext.label": "PRICE CHANGES",
      "pricing.longContext.text": "長文脈では料金が異なる場合があります。モデル価格、割引、cacheの扱い、契約条件は変更される可能性があるため、実際の請求は公式料金と利用状況を確認してください。",
      "privacy.title": "Nospaceは<br><span>データを保持しません。</span>",
      "privacy.lede": "Nospaceは、選んだAPIを直接利用します。独自サーバーを経由しません。",
      "privacy.card.label": "API DESTINATION",
      "privacy.card.title": "入力文は、<br><strong>選んだAPIへ。</strong>",
      "privacy.card.text": "NospaceはOpenAI APIまたはOpenRouter APIを直接利用します。入力文と候補生成の指示は選択したAPIへ送信しますが、Nospaceの独自サーバーや他の場所には送りません。",
      "privacy.card.destination": "送信先",
      "privacy.card.request": "APIリクエスト",
      "privacy.card.tag": "独自サーバーには送信しません",
      "privacy.footnotes.keyTitle": "APIキー",
      "privacy.footnotes.keyText": "macOSのキーチェーンに保存します。",
      "privacy.footnotes.permissionTitle": "権限がないとき",
      "privacy.footnotes.permissionText": "候補はクリップボードから手動で貼り付けできます。",
      "privacy.footnotes.storageTitle": "アプリの保存",
      "privacy.footnotes.storageText": "入力と候補はディスクに保存しません。",
      "privacy.analytics.title": "Webサイトのアクセス解析",
      "privacy.analytics.text": "このWebサイトではGoogle Analyticsを使用します。同意するとCookieを使ってアクセス状況を分析します。同意しない場合も、Cookieを使用しない限定的な情報がGoogleに送信されます。",
      "privacy.analytics.link": "Googleによる情報の利用について",
      "privacy.analytics.linkLabel": "Googleによる情報の利用について見る（新しいタブ）",
      "privacy.analytics.privacyLink": "Googleのプライバシーポリシー",
      "privacy.analytics.privacyLinkLabel": "Googleのプライバシーポリシーを見る（新しいタブ）",
      "consent.title": "アクセス解析の設定",
      "consent.label": "ANALYTICS CHOICE",
      "consent.text": "同意すると、Google AnalyticsがCookieを使用してアクセス状況を分析します。同意しない場合も、Cookieを使用しない限定的な情報がGoogleに送信されます。選択は後から変更できます。",
      "consent.details": "データの扱いを見る",
      "consent.deny": "同意しない",
      "consent.grant": "同意する",
      "consent.settings": "Cookie設定",
      "download.title": "次の一文を、<br><span>すぐ書こう。</span>",
      "download.lede": "macOS 14以降。すぐに始められます。",
      "download.linkLabel": "Nospaceをダウンロード（新しいタブ）",
      "download.socialLabel": "LATEST UPDATES",
      "download.socialText": "リリースや使い方の更新をお知らせします。",
      "download.socialLink": "@nospace_app をフォロー",
      "download.socialAria": "Nospace公式Xアカウントをフォロー（新しいタブ）",
      "footer.tagline": "入力を、考える速さに。",
      "footer.xAria": "Nospace公式Xアカウントを開く（新しいタブ）"
    }),
    "zh-Hans": locale({
      "meta.description": "即使输入有错字或拼音不完整，也能用 AI 写出自然文字，并将选中的结果插入当前应用。",
      "document.title": "Nospace — 按照思考的速度写作。",
      "skip.main": "跳转到主要内容",
      "brand.homeLabel": "返回 Nospace 首页",
      "nav.label": "主导航",
      "nav.flow": "工作方式",
      "nav.cost": "费用",
      "nav.privacy": "数据与权限",
      "nav.download": "下载",
      "hero.title": "<span class=\"hero__headline-line hero__headline-line--ink\">按照思考的速度</span><br><em>写下来。</em>",
      "hero.lede": "不用担心错字，先把想法输入下来，再让 Nospace 整理成自然文字。",
      "hero.privacyLink": "了解数据如何处理",
      "hero.note": "你的输入会发送到所选 API 以生成候选结果。API 密钥保存在 macOS 钥匙串中。",
      "hero.shortcutLabel": "按 Shift Space 打开输入面板",
      "hero.openWith": "按快捷键打开",
      "hero.visualAria": "Nospace 演示：输入拼音，查看自然候选结果，并将所选文字插入当前应用",
      "hero.demoLanguage": "简体中文",
      "hero.demoMeta": "产品演示",
      "hero.demoTogglePause": "暂停演示视频",
      "hero.demoTogglePlay": "播放演示视频",
      "hero.demoPause": "暂停",
      "hero.demoPlay": "播放",
      "hero.demoEditorSubtitle": "已编辑",
      "hero.demoEditorMode": "纯文本",
      "hero.demoEditorStatus": "第 1 行　字符：0　位置：0",
      "hero.demoPanelSettings": "演示设置",
      "hero.demoPanelInputPlaceholder": "输入拼音…",
      "hero.demoPanelLanguageEnglish": "English",
      "hero.demoPanelLanguageTarget": "简体中文",
      "hero.demoPanelConvert": "生成",
      "hero.demoPanelShortcuts": "↵ 换行",
      "hero.demoPanelLoading": "正在重构为自然中文",
      "hero.demoPanelCancel": "取消",
      "hero.demoPanelCandidateCount": "{count} 个候选",
      "hero.demoPanelCandidateCountOne": "{count} 个候选",
      "hero.demoPanelAdjust": "调整",
      "hero.demoPanelRegenerate": "重新生成",
      "hero.demoPanelAddDictionary": "添加到词典",
      "hero.demoPanelEdit": "编辑　↪",
      "hero.demoPanelTranslate": "翻译　⌘T",
      "hero.demoPanelSelect": "↑↓ 选择",
      "hero.demoPanelInsert": "↵ 插入",
      "hero.demoPanelClose": "esc 关闭",
      "hero.sr": "无声产品演示展示了从拼音输入到自然候选结果的过程，以及将所选结果返回当前应用。",
      "hero.visualFootInput": "先输入粗略版本",
      "hero.visualFootSelect": "选择一个候选",
      "eyebrow.howItFlows": "工作流程",
      "eyebrow.plainOnPurpose": "清晰，正是如此",
      "eyebrow.startTyping": "开始输入",
      "eyebrow.websiteAnalytics": "网站分析",
      "demo.input": "输入",
      "demo.rawInput": "nospacelujiguanshidacuolezichengziranjuzi",
      "demo.resultOne": "有了 Nospace，即使打错字，也能把你的想法快速变成自然的句子。",
      "demo.resultTwo": "有了 Nospace，错别字也能在几秒内变成自然文字。",
      "demo.resultThree": "Nospace 会把粗略的想法整理成清晰自然的文字。",
      "demo.resultFour": "即使输入不完美，也能变成完整的句子。",
      "demo.resultFive": "有了 Nospace，粗略输入也能变成读起来更自然的句子。",
      "demo.resultSix": "Nospace 会把快速写下的想法整理成可以直接使用的文字。",
      "demo.resultSeven": "先输入你的想法，剩下的交给 Nospace 自然地润色。",
      "demo.resultEight": "即使输入不完整，Nospace 也能帮你保持句子的连贯。",
      "demo.editorText": "有了 Nospace，即使打错字，也能把你的想法快速变成自然的句子。",
      "demo.editorStats": "第 1 行　字符：43　位置：43",
      "demo.select": "↑↓ 选择",
      "demo.insert": "↵ 插入",
      "demo.close": "esc 关闭",
      "process.title": "让输入跟上，<br><span>思考的速度。</span>",
      "process.lede": "输入。选择候选。句子回到你开始的地方。不必在多余的窗口之间来回切换。",
      "process.input.label": "输入",
      "process.input.title": "想到什么，<br>就输入什么。",
      "process.input.text": "错别字也没关系。Nospace 会理解上下文，整理出自然的候选结果。",
      "process.input.example": "nospacelujiguanshidacuolezichengziranjuzi",
      "process.reconstruct.label": "重构",
      "process.reconstruct.title": "AI 生成五个<br>自然候选。",
      "process.reconstruct.text": "候选结果会结合上下文，因此不必反复按空格寻找正确转换。",
      "process.reconstruct.example": "有了 Nospace，即使打错字，也能把你的想法快速变成自然的句子。",
      "process.insert.label": "插入",
      "process.insert.title": "把句子放回<br>原来的应用。",
      "process.insert.text": "用快捷键打开，选择结果，文字就会回到原来的焦点位置。",
      "process.insert.app": "备忘录",
      "process.insert.example": "有了 Nospace，即使打错字，也能把你的想法快速变成自然的句子。",
      "pricing.eyebrow": "费用 / 每份稿件",
      "pricing.title": "5 美元，<br><span>约 1 万页稿纸。</span>",
      "pricing.lede": "Nospace 本身不收取使用费。这个估算根据实测的长文本生成，展示 5 美元大约可以完成多少内容。",
      "pricing.callout.title": "这是基于实测的估算。",
      "pricing.callout.text": "模型价格、缓存和合同条件变化后，实际费用也会变化。",
      "pricing.ledger.unit": "长文本生成 / 实测",
      "pricing.ledger.estimate": "估算 / 美元",
      "pricing.measure.title": "一页稿纸",
      "pricing.measure.text": "1,238 个日文字符<br>输出 / 400 字",
      "pricing.model.label": "模型",
      "pricing.model.detail": "包含系统提示词",
      "pricing.provider.meta": "实测响应 / 一次调用",
      "pricing.provider.estimate": "每次调用估算",
      "pricing.rate.input": "输入",
      "pricing.rate.cachedInput": "缓存输入",
      "pricing.rate.cacheWrite": "写入缓存",
      "pricing.rate.output": "输出",
      "pricing.provider.link": "查看官方价格",
      "pricing.provider.linkLabel": "在新标签页查看 GPT-5.6 Luna 官方价格",
      "pricing.assumptions.label": "测量",
      "pricing.assumptions.text": "我们实测了一次包含 3,981 个系统指令字符的 Responses API 请求：输入 1,156 tokens、输出 986 tokens、输出 1,238 个字符。按每页稿纸 400 字计算，一次约 3.1 页，5 美元约 3,400 次调用或 1 万页。",
      "pricing.priceNote.label": "价格说明",
      "pricing.priceNote.text": "按短上下文价格计算：输入 $0.20 / M、缓存输入 $0.02 / M、写入缓存 $0.25 / M、输出 $1.20 / M，总计 $0.00147205。",
      "pricing.longContext.label": "价格变化",
      "pricing.longContext.text": "长上下文价格可能不同。模型价格、折扣、缓存处理方式和合同条件都可能变化，请以官方价格和实际用量为准。",
      "privacy.title": "Nospace 不会<br><span>保存你的数据。</span>",
      "privacy.lede": "Nospace 直接连接你选择的 API，不经过 Nospace 自己的中继服务器。",
      "privacy.card.label": "API 目的地",
      "privacy.card.title": "你的文字会发送到<br><strong>所选的 API。</strong>",
      "privacy.card.text": "Nospace 直接使用 OpenAI API 或 OpenRouter API。你的输入和候选生成指令会发送到所选 API，不会发送到 Nospace 自有服务器或其他目的地。",
      "privacy.card.destination": "发送目的地",
      "privacy.card.request": "API 请求",
      "privacy.card.tag": "不经过 Nospace 中继服务器",
      "privacy.footnotes.keyTitle": "API 密钥",
      "privacy.footnotes.keyText": "保存在 macOS 钥匙串中。",
      "privacy.footnotes.permissionTitle": "没有权限时",
      "privacy.footnotes.permissionText": "可以从剪贴板手动粘贴所选结果。",
      "privacy.footnotes.storageTitle": "应用存储",
      "privacy.footnotes.storageText": "输入和候选结果不会保存到磁盘。",
      "privacy.analytics.title": "网站访问分析",
      "privacy.analytics.text": "本网站使用 Google Analytics。选择同意后，Cookie 会用于分析访问情况；即使不同意，仍会向 Google 发送有限的无 Cookie 信息。",
      "privacy.analytics.link": "Google 如何使用信息",
      "privacy.analytics.linkLabel": "在新标签页查看 Google 如何使用信息",
      "privacy.analytics.privacyLink": "Google 隐私政策",
      "privacy.analytics.privacyLinkLabel": "在新标签页查看 Google 隐私政策",
      "consent.title": "访问分析设置",
      "consent.label": "分析选择",
      "consent.text": "同意后，Google Analytics 会使用 Cookie 分析访问情况。不同意时，仍会向 Google 发送有限的无 Cookie 信息。之后可以更改选择。",
      "consent.details": "查看数据处理方式",
      "consent.deny": "不同意",
      "consent.grant": "同意",
      "consent.settings": "Cookie 设置",
      "download.title": "现在就写下<br><span>下一句话。</span>",
      "download.lede": "macOS 14 或更高版本。马上开始。",
      "download.linkLabel": "在新标签页下载 Nospace",
      "download.socialLabel": "最新消息",
      "download.socialText": "在 X 上关注发布和使用方式更新。",
      "download.socialLink": "关注 @nospace_app",
      "download.socialAria": "在新标签页关注 Nospace 官方 X 账号",
      "footer.tagline": "让输入跟上思考的速度。",
      "footer.xAria": "在新标签页打开 Nospace 官方 X 账号"
    }),
    "zh-Hant": locale({
      "meta.description": "即使輸入有錯字或拼音不完整，也能用 AI 寫出自然文字，並將選取的結果插入目前的應用程式。",
      "document.title": "Nospace — 按照思考的速度寫作。",
      "skip.main": "跳至主要內容",
      "brand.homeLabel": "返回 Nospace 首頁",
      "nav.label": "主導覽列",
      "nav.flow": "運作方式",
      "nav.cost": "費用",
      "nav.privacy": "資料與權限",
      "nav.download": "下載",
      "hero.title": "<span class=\"hero__headline-line hero__headline-line--ink\">按照思考的速度</span><br><em>寫下來。</em>",
      "hero.lede": "不用擔心錯字，先把想法輸入下來，再讓 Nospace 整理成自然文字。",
      "hero.privacyLink": "了解資料如何處理",
      "hero.note": "你的輸入會傳送到所選 API 以產生候選結果。API 金鑰保存在 macOS 鑰匙圈中。",
      "hero.shortcutLabel": "按 Shift Space 開啟輸入面板",
      "hero.openWith": "按快速鍵開啟",
      "hero.visualAria": "Nospace 示範：輸入拼音，查看自然候選結果，並將選取的文字插入目前的應用程式",
      "hero.demoLanguage": "繁體中文",
      "hero.demoMeta": "產品示範",
      "hero.demoTogglePause": "暫停示範影片",
      "hero.demoTogglePlay": "播放示範影片",
      "hero.demoPause": "暫停",
      "hero.demoPlay": "播放",
      "hero.demoEditorSubtitle": "已編輯",
      "hero.demoEditorMode": "純文字",
      "hero.demoEditorStatus": "第 1 行　字元：0　位置：0",
      "hero.demoPanelSettings": "示範設定",
      "hero.demoPanelInputPlaceholder": "輸入拼音…",
      "hero.demoPanelLanguageEnglish": "English",
      "hero.demoPanelLanguageTarget": "繁體中文",
      "hero.demoPanelConvert": "產生",
      "hero.demoPanelShortcuts": "↵ 換行",
      "hero.demoPanelLoading": "正在重構為自然中文",
      "hero.demoPanelCancel": "取消",
      "hero.demoPanelCandidateCount": "{count} 個候選",
      "hero.demoPanelCandidateCountOne": "{count} 個候選",
      "hero.demoPanelAdjust": "調整",
      "hero.demoPanelRegenerate": "重新生成",
      "hero.demoPanelAddDictionary": "加入詞典",
      "hero.demoPanelEdit": "編輯　↪",
      "hero.demoPanelTranslate": "翻譯　⌘T",
      "hero.demoPanelSelect": "↑↓ 選取",
      "hero.demoPanelInsert": "↵ 插入",
      "hero.demoPanelClose": "esc 關閉",
      "hero.sr": "無聲產品示範展示了從拼音輸入到自然候選結果的過程，以及將選取結果返回目前應用程式。",
      "hero.visualFootInput": "先輸入粗略版本",
      "hero.visualFootSelect": "選擇一個候選",
      "eyebrow.howItFlows": "工作流程",
      "eyebrow.plainOnPurpose": "清楚，正是如此",
      "eyebrow.startTyping": "開始輸入",
      "eyebrow.websiteAnalytics": "網站分析",
      "demo.input": "輸入",
      "demo.rawInput": "nospaceliujiguanxidacuolezichengziranjuzi",
      "demo.resultOne": "有了 Nospace，即使打錯字，也能把你的想法快速變成自然的句子。",
      "demo.resultTwo": "有了 Nospace，錯別字也能在幾秒內變成自然文字。",
      "demo.resultThree": "Nospace 會把粗略的想法整理成清楚自然的文字。",
      "demo.resultFour": "即使輸入不完美，也能變成完整的句子。",
      "demo.resultFive": "有了 Nospace，粗略輸入也能變成讀起來更自然的句子。",
      "demo.resultSix": "Nospace 會把快速寫下的想法整理成可以直接使用的文字。",
      "demo.resultSeven": "先輸入你的想法，剩下的交給 Nospace 自然地潤飾。",
      "demo.resultEight": "即使輸入不完整，Nospace 也能幫你保持句子的連貫。",
      "demo.editorText": "有了 Nospace，即使打錯字，也能把你的想法快速變成自然的句子。",
      "demo.editorStats": "第 1 行　字元：42　位置：42",
      "demo.select": "↑↓ 選取",
      "demo.insert": "↵ 插入",
      "demo.close": "esc 關閉",
      "process.title": "讓輸入跟上，<br><span>思考的速度。</span>",
      "process.lede": "輸入。選擇候選。句子回到你開始的地方。不必在多餘的視窗之間來回切換。",
      "process.input.label": "輸入",
      "process.input.title": "想到什麼，<br>就輸入什麼。",
      "process.input.text": "錯字也沒關係。Nospace 會理解上下文，整理出自然的候選結果。",
      "process.input.example": "nospaceliujiguanxidacuolezichengziranjuzi",
      "process.reconstruct.label": "重構",
      "process.reconstruct.title": "AI 產生五個<br>自然候選。",
      "process.reconstruct.text": "候選結果會結合上下文，因此不必反覆按空白鍵尋找正確轉換。",
      "process.reconstruct.example": "有了 Nospace，即使打錯字，也能把你的想法快速變成自然的句子。",
      "process.insert.label": "插入",
      "process.insert.title": "把句子放回<br>原來的應用程式。",
      "process.insert.text": "用快速鍵開啟，選擇結果，文字就會回到原來的焦點位置。",
      "process.insert.app": "備忘錄",
      "process.insert.example": "有了 Nospace，即使打錯字，也能把你的想法快速變成自然的句子。",
      "pricing.eyebrow": "費用 / 每份稿件",
      "pricing.title": "5 美元，<br><span>約 1 萬頁稿紙。</span>",
      "pricing.lede": "Nospace 本身不收取使用費。這個估算根據實測的長文生成，展示 5 美元大約可以完成多少內容。",
      "pricing.callout.title": "這是根據實測的估算。",
      "pricing.callout.text": "模型價格、快取和合約條件變化後，實際費用也會變化。",
      "pricing.ledger.unit": "長文生成 / 實測",
      "pricing.ledger.estimate": "估算 / 美元",
      "pricing.measure.title": "一頁稿紙",
      "pricing.measure.text": "1,238 個日文字符<br>輸出 / 400 字",
      "pricing.model.label": "模型",
      "pricing.model.detail": "包含系統提示詞",
      "pricing.provider.meta": "實測回應 / 一次呼叫",
      "pricing.provider.estimate": "每次呼叫估算",
      "pricing.rate.input": "輸入",
      "pricing.rate.cachedInput": "快取輸入",
      "pricing.rate.cacheWrite": "寫入快取",
      "pricing.rate.output": "輸出",
      "pricing.provider.link": "查看官方價格",
      "pricing.provider.linkLabel": "在新分頁查看 GPT-5.6 Luna 官方價格",
      "pricing.assumptions.label": "測量",
      "pricing.assumptions.text": "我們實測了一次包含 3,981 個系統指令字元的 Responses API 請求：輸入 1,156 tokens、輸出 986 tokens、輸出 1,238 個字元。按每頁稿紙 400 字計算，一次約 3.1 頁，5 美元約 3,400 次呼叫或 1 萬頁。",
      "pricing.priceNote.label": "價格說明",
      "pricing.priceNote.text": "按短上下文價格計算：輸入 $0.20 / M、快取輸入 $0.02 / M、寫入快取 $0.25 / M、輸出 $1.20 / M，總計 $0.00147205。",
      "pricing.longContext.label": "價格變化",
      "pricing.longContext.text": "長上下文價格可能不同。模型價格、折扣、快取處理方式和合約條件都可能變化，請以官方價格和實際用量為準。",
      "privacy.title": "Nospace 不會<br><span>保存你的資料。</span>",
      "privacy.lede": "Nospace 直接連接你選擇的 API，不經過 Nospace 自己的中繼伺服器。",
      "privacy.card.label": "API 目的地",
      "privacy.card.title": "你的文字會傳送到<br><strong>所選的 API。</strong>",
      "privacy.card.text": "Nospace 直接使用 OpenAI API 或 OpenRouter API。你的輸入和候選生成指令會傳送到所選 API，不會傳送到 Nospace 自有伺服器或其他目的地。",
      "privacy.card.destination": "傳送目的地",
      "privacy.card.request": "API 請求",
      "privacy.card.tag": "不經過 Nospace 中繼伺服器",
      "privacy.footnotes.keyTitle": "API 金鑰",
      "privacy.footnotes.keyText": "保存在 macOS 鑰匙圈中。",
      "privacy.footnotes.permissionTitle": "沒有權限時",
      "privacy.footnotes.permissionText": "可以從剪貼簿手動貼上所選結果。",
      "privacy.footnotes.storageTitle": "應用程式儲存",
      "privacy.footnotes.storageText": "輸入和候選結果不會保存到磁碟。",
      "privacy.analytics.title": "網站存取分析",
      "privacy.analytics.text": "本網站使用 Google Analytics。同意後，Cookie 會用於分析訪問情況；即使不同意，仍會向 Google 傳送有限的無 Cookie 資訊。",
      "privacy.analytics.link": "Google 如何使用資訊",
      "privacy.analytics.linkLabel": "在新分頁查看 Google 如何使用資訊",
      "privacy.analytics.privacyLink": "Google 隱私權政策",
      "privacy.analytics.privacyLinkLabel": "在新分頁查看 Google 隱私權政策",
      "consent.title": "存取分析設定",
      "consent.label": "分析選擇",
      "consent.text": "同意後，Google Analytics 會使用 Cookie 分析訪問情況。不同意時，仍會向 Google 傳送有限的無 Cookie 資訊。之後可以更改選擇。",
      "consent.details": "查看資料處理方式",
      "consent.deny": "不同意",
      "consent.grant": "同意",
      "consent.settings": "Cookie 設定",
      "download.title": "現在就寫下<br><span>下一句話。</span>",
      "download.lede": "macOS 14 或以上版本。馬上開始。",
      "download.linkLabel": "在新分頁下載 Nospace",
      "download.socialLabel": "最新消息",
      "download.socialText": "在 X 上關注發布和使用方式更新。",
      "download.socialLink": "關注 @nospace_app",
      "download.socialAria": "在新分頁關注 Nospace 官方 X 帳號",
      "footer.tagline": "讓輸入跟上思考的速度。",
      "footer.xAria": "在新分頁開啟 Nospace 官方 X 帳號"
    }),
    es: locale({
      "meta.description": "Convierte entradas fonéticas y errores en texto natural con IA e inserta el resultado elegido en la aplicación que ya usabas.",
      "document.title": "Nospace — Escribe al ritmo de tus ideas.",
      "skip.main": "Saltar al contenido principal",
      "brand.homeLabel": "Ir a la página principal de Nospace",
      "nav.label": "Navegación principal",
      "nav.flow": "Cómo funciona",
      "nav.cost": "Coste",
      "nav.privacy": "Datos y permisos",
      "nav.download": "Descargar",
      "hero.title": "<span class=\"hero__headline-line hero__headline-line--ink\">Escribe al ritmo</span><br><em>de tus ideas.</em>",
      "hero.lede": "Escribe sin frenar por los errores y deja que Nospace convierta el borrador en algo natural.",
      "hero.privacyLink": "Ver cómo se usan los datos",
      "hero.note": "Tu texto se envía a la API que elijas para generar candidatos. La clave de API se guarda en el Llavero de macOS.",
      "hero.shortcutLabel": "Abre el panel de entrada con Shift Space",
      "hero.openWith": "ABRIR CON",
      "hero.visualAria": "Demostración de Nospace: escribe texto fonético, revisa candidatos naturales e inserta el resultado elegido",
      "hero.demoLanguage": "Español",
      "hero.demoMeta": "DEMOSTRACIÓN",
      "hero.demoTogglePause": "Pausar el vídeo",
      "hero.demoTogglePlay": "Reproducir el vídeo",
      "hero.demoPause": "PAUSA",
      "hero.demoPlay": "REPRODUCIR",
      "hero.demoEditorSubtitle": "Editado",
      "hero.demoEditorMode": "Texto sin formato",
      "hero.demoEditorStatus": "Línea: 1　Caracteres: 0　Posición: 0",
      "hero.demoPanelSettings": "Ajustes de demostración",
      "hero.demoPanelInputPlaceholder": "Escribe fonéticamente…",
      "hero.demoPanelLanguageEnglish": "English",
      "hero.demoPanelLanguageTarget": "Español",
      "hero.demoPanelConvert": "Generar",
      "hero.demoPanelShortcuts": "↵ Nueva línea",
      "hero.demoPanelLoading": "Reconstruyendo texto natural",
      "hero.demoPanelCancel": "Cancelar",
      "hero.demoPanelCandidateCount": "{count} candidatos",
      "hero.demoPanelCandidateCountOne": "{count} candidato",
      "hero.demoPanelAdjust": "Ajustar",
      "hero.demoPanelRegenerate": "Regenerar",
      "hero.demoPanelAddDictionary": "Añadir al diccionario",
      "hero.demoPanelEdit": "Editar　↪",
      "hero.demoPanelTranslate": "Traducir ⌘T",
      "hero.demoPanelSelect": "↑↓ Seleccionar",
      "hero.demoPanelInsert": "↵ Insertar",
      "hero.demoPanelClose": "esc Cerrar",
      "hero.sr": "Una demostración sin sonido muestra cómo una entrada fonética se convierte en candidatos naturales y cómo el resultado vuelve a la aplicación enfocada.",
      "hero.visualFootInput": "Escribe la versión aproximada",
      "hero.visualFootSelect": "Elige un candidato",
      "eyebrow.howItFlows": "CÓMO FUNCIONA",
      "eyebrow.plainOnPurpose": "CLARO A PROPÓSITO",
      "eyebrow.startTyping": "EMPIEZA A ESCRIBIR",
      "eyebrow.websiteAnalytics": "ANÁLISIS DEL SITIO",
      "demo.input": "ENTRADA",
      "demo.rawInput": "connospaceinclusoconerrorestusideassevuelvenfrasesnaturales",
      "demo.resultOne": "Con Nospace, incluso con errores, tus ideas se convierten rápidamente en frases naturales.",
      "demo.resultTwo": "Con Nospace, los errores se convierten en texto natural en segundos.",
      "demo.resultThree": "Nospace convierte pensamientos rápidos en texto claro y natural.",
      "demo.resultFour": "Incluso una entrada imperfecta puede acabar en una frase pulida.",
      "demo.resultFive": "Con Nospace, una entrada rápida se convierte en una frase que suena natural.",
      "demo.resultSix": "Nospace ordena tus ideas rápidas en un texto listo para usar.",
      "demo.resultSeven": "Escribe primero la idea y deja que Nospace la vuelva natural.",
      "demo.resultEight": "Aunque falten detalles, Nospace mantiene el hilo de la frase.",
      "demo.editorText": "Con Nospace, incluso con errores, tus ideas se convierten rápidamente en frases naturales.",
      "demo.editorStats": "Línea: 1　Caracteres: 103　Posición: 103",
      "demo.select": "↑↓ Seleccionar",
      "demo.insert": "↵ Insertar",
      "demo.close": "esc Cerrar",
      "process.title": "Escribe al ritmo,<br><span>de tus ideas.</span>",
      "process.lede": "Escribe. Elige un candidato. Tu frase vuelve al lugar donde empezaste, sin otra ventana que recorrer.",
      "process.input.label": "ENTRADA",
      "process.input.title": "Escribe la idea<br>tal como llega.",
      "process.input.text": "Los errores no importan. Nospace entiende el contexto y crea candidatos naturales.",
      "process.input.example": "connospaceinclusoconerrorestusideassevuelvenfrasesnaturales",
      "process.reconstruct.label": "RECONSTRUIR",
      "process.reconstruct.title": "La IA crea cinco<br>opciones naturales.",
      "process.reconstruct.text": "Los candidatos siguen el contexto, para que pases menos tiempo buscando la conversión correcta.",
      "process.reconstruct.example": "Con Nospace, incluso con errores, tus ideas se convierten rápidamente en frases naturales.",
      "process.insert.label": "INSERTAR",
      "process.insert.title": "Devuelve la frase<br>a tu aplicación.",
      "process.insert.text": "Ábrelo con un atajo, elige un resultado y vuelve a la posición que tenía el foco.",
      "process.insert.app": "Notas",
      "process.insert.example": "Con Nospace, incluso con errores, tus ideas se convierten rápidamente en frases naturales.",
      "pricing.eyebrow": "COSTE / POR MANUSCRITO",
      "pricing.title": "Cinco dólares,<br><span>unas 10.000 páginas.</span>",
      "pricing.lede": "Nospace no cobra por usarlo. Esta estimación parte de una generación larga medida para mostrar qué cubren cinco dólares.",
      "pricing.callout.title": "Es una estimación medida.",
      "pricing.callout.text": "El importe real cambia con los precios del modelo, la caché y las condiciones del contrato.",
      "pricing.ledger.unit": "GENERACIÓN LARGA / MEDIDA",
      "pricing.ledger.estimate": "ESTIMACIÓN / USD",
      "pricing.measure.title": "Una página de manuscrito",
      "pricing.measure.text": "1.238 caracteres japoneses<br>SALIDA / 400 caracteres",
      "pricing.model.label": "MODELO",
      "pricing.model.detail": "incluye el prompt del sistema",
      "pricing.provider.meta": "respuesta medida / una llamada",
      "pricing.provider.estimate": "estimado por llamada",
      "pricing.rate.input": "ENTRADA",
      "pricing.rate.cachedInput": "ENTRADA EN CACHÉ",
      "pricing.rate.cacheWrite": "ESCRITURA DE CACHÉ",
      "pricing.rate.output": "SALIDA",
      "pricing.provider.link": "Ver precios oficiales",
      "pricing.provider.linkLabel": "Ver los precios oficiales de GPT-5.6 Luna en una pestaña nueva",
      "pricing.assumptions.label": "MEDICIÓN",
      "pricing.assumptions.text": "Medimos una solicitud de Responses API con 3.981 caracteres de instrucciones del sistema: 1.156 tokens de entrada, 986 de salida y 1.238 caracteres de salida. A 400 caracteres por página, una llamada son unas 3,1 páginas y cinco dólares son unas 3.400 llamadas o 10.000 páginas.",
      "pricing.priceNote.label": "NOTA DE PRECIO",
      "pricing.priceNote.text": "Con las tarifas de contexto corto, el coste medido es $0.00147205 por llamada.",
      "pricing.longContext.label": "CAMBIOS DE PRECIO",
      "pricing.longContext.text": "Las tarifas de contexto largo pueden variar. Comprueba los precios oficiales y tu uso para conocer el importe real.",
      "privacy.title": "Nospace no<br><span>guarda tus datos.</span>",
      "privacy.lede": "Nospace se comunica directamente con la API que eliges. No hay un servidor intermedio de Nospace.",
      "privacy.card.label": "DESTINO DE LA API",
      "privacy.card.title": "Tu texto va<br><strong>a la API elegida.</strong>",
      "privacy.card.text": "Nospace usa directamente la API de OpenAI o OpenRouter. Tu entrada y las instrucciones de reconstrucción van a la API seleccionada, no a un servidor de Nospace ni a otro destino.",
      "privacy.card.destination": "Destino",
      "privacy.card.request": "Solicitud API",
      "privacy.card.tag": "Sin servidor intermedio de Nospace",
      "privacy.footnotes.keyTitle": "Clave de API",
      "privacy.footnotes.keyText": "Se guarda en el Llavero de macOS.",
      "privacy.footnotes.permissionTitle": "Sin permiso",
      "privacy.footnotes.permissionText": "Pega manualmente el resultado desde el portapapeles.",
      "privacy.footnotes.storageTitle": "Almacenamiento de la app",
      "privacy.footnotes.storageText": "La entrada y los candidatos no se guardan en el disco.",
      "privacy.analytics.title": "Análisis del sitio web",
      "privacy.analytics.text": "Este sitio usa Google Analytics. Si aceptas, las cookies ayudan a analizar las visitas. Si rechazas, se envía a Google información limitada sin cookies.",
      "privacy.analytics.link": "Cómo usa Google la información",
      "privacy.analytics.linkLabel": "Ver cómo usa Google la información en una pestaña nueva",
      "privacy.analytics.privacyLink": "Política de privacidad de Google",
      "privacy.analytics.privacyLinkLabel": "Ver la política de privacidad de Google en una pestaña nueva",
      "consent.title": "Ajustes de análisis",
      "consent.label": "OPCIÓN DE ANÁLISIS",
      "consent.text": "Si aceptas, Google Analytics usa cookies para analizar las visitas. Si rechazas, se envía a Google información limitada sin cookies. Puedes cambiar esta elección más adelante.",
      "consent.details": "Ver cómo se usan los datos",
      "consent.deny": "Rechazar",
      "consent.grant": "Aceptar",
      "consent.settings": "Ajustes de cookies",
      "download.title": "Escribe la siguiente frase<br><span>ahora mismo.</span>",
      "download.lede": "macOS 14 o posterior. Empieza en un momento.",
      "download.linkLabel": "Descargar Nospace en una pestaña nueva",
      "download.socialLabel": "ÚLTIMAS NOVEDADES",
      "download.socialText": "Sigue las novedades de lanzamientos y formas de usar Nospace.",
      "download.socialLink": "Seguir a @nospace_app",
      "download.socialAria": "Seguir la cuenta oficial de Nospace en X en una pestaña nueva",
      "footer.tagline": "Escribe al ritmo de tus ideas.",
      "footer.xAria": "Abrir la cuenta oficial de Nospace en X en una pestaña nueva"
    }),
    hi: locale({
      "meta.description": "टाइपो और असमान ध्वन्यात्मक इनपुट को AI की मदद से स्वाभाविक लेखन में बदलें और चुना हुआ परिणाम उसी ऐप में डालें।",
      "document.title": "Nospace — विचारों की गति से लिखें।",
      "skip.main": "मुख्य सामग्री पर जाएँ",
      "brand.homeLabel": "Nospace होमपेज पर जाएँ",
      "nav.label": "मुख्य नेविगेशन",
      "nav.flow": "यह कैसे काम करता है",
      "nav.cost": "लागत",
      "nav.privacy": "डेटा और अनुमतियाँ",
      "nav.download": "डाउनलोड",
      "hero.title": "<span class=\"hero__headline-line hero__headline-line--ink\">विचारों की गति से</span><br><em>लिखें।</em>",
      "hero.lede": "गलतियों पर रुकें नहीं। जल्दी से लिखें और Nospace को उसे स्वाभाविक वाक्य बनाने दें।",
      "hero.privacyLink": "डेटा का उपयोग देखें",
      "hero.note": "उम्मीदवार बनाने के लिए आपका पाठ चुने हुए API को भेजा जाता है। API कुंजी macOS Keychain में रहती है।",
      "hero.shortcutLabel": "Shift Space से इनपुट पैनल खोलें",
      "hero.openWith": "इससे खोलें",
      "hero.visualAria": "Nospace डेमो: ध्वन्यात्मक पाठ लिखें, स्वाभाविक विकल्प देखें और चुना हुआ परिणाम ऐप में डालें",
      "hero.demoLanguage": "हिन्दी",
      "hero.demoMeta": "उत्पाद डेमो",
      "hero.demoTogglePause": "डेमो वीडियो रोकें",
      "hero.demoTogglePlay": "डेमो वीडियो चलाएँ",
      "hero.demoPause": "रोकें",
      "hero.demoPlay": "चलाएँ",
      "hero.demoEditorSubtitle": "संपादित",
      "hero.demoEditorMode": "सादा पाठ",
      "hero.demoEditorStatus": "पंक्ति: 1　अक्षर: 0　स्थिति: 0",
      "hero.demoPanelSettings": "डेमो सेटिंग्स",
      "hero.demoPanelInputPlaceholder": "ध्वन्यात्मक रूप से लिखें…",
      "hero.demoPanelLanguageEnglish": "English",
      "hero.demoPanelLanguageTarget": "हिन्दी",
      "hero.demoPanelConvert": "बनाएँ",
      "hero.demoPanelShortcuts": "↵ नई पंक्ति",
      "hero.demoPanelLoading": "स्वाभाविक पाठ बनाया जा रहा है",
      "hero.demoPanelCancel": "रद्द करें",
      "hero.demoPanelCandidateCount": "{count} विकल्प",
      "hero.demoPanelCandidateCountOne": "{count} विकल्प",
      "hero.demoPanelAdjust": "समायोजित करें",
      "hero.demoPanelRegenerate": "फिर से बनाएँ",
      "hero.demoPanelAddDictionary": "शब्दकोश में जोड़ें",
      "hero.demoPanelEdit": "संपादित करें　↪",
      "hero.demoPanelTranslate": "अनुवाद करें ⌘T",
      "hero.demoPanelSelect": "↑↓ चुनें",
      "hero.demoPanelInsert": "↵ डालें",
      "hero.demoPanelClose": "esc बंद करें",
      "hero.sr": "बिना आवाज़ वाला डेमो ध्वन्यात्मक इनपुट से स्वाभाविक विकल्प बनने और चुने हुए परिणाम के ऐप में लौटने की प्रक्रिया दिखाता है।",
      "hero.visualFootInput": "मोटा मसौदा लिखें",
      "hero.visualFootSelect": "एक विकल्प चुनें",
      "eyebrow.howItFlows": "यह कैसे चलता है",
      "eyebrow.plainOnPurpose": "जानबूझकर स्पष्ट",
      "eyebrow.startTyping": "लिखना शुरू करें",
      "eyebrow.websiteAnalytics": "वेबसाइट विश्लेषण",
      "demo.input": "इनपुट",
      "demo.rawInput": "nospacekemadadsebhiaapkevicharsahajvakyabanjatehain",
      "demo.resultOne": "Nospace के साथ, गलतियाँ होने पर भी आपके विचार जल्दी स्वाभाविक वाक्यों में बदल जाते हैं।",
      "demo.resultTwo": "Nospace के साथ, टाइपो भी कुछ ही सेकंड में स्वाभाविक लेखन बन जाते हैं।",
      "demo.resultThree": "Nospace अधूरे विचारों को स्पष्ट और स्वाभाविक पाठ में बदलता है।",
      "demo.resultFour": "अपूर्ण इनपुट भी एक सुंदर वाक्य बन सकता है।",
      "demo.resultFive": "Nospace के साथ तेज़ी से लिखा इनपुट भी स्वाभाविक वाक्य बन जाता है।",
      "demo.resultSix": "Nospace आपके जल्दी लिखे विचारों को उपयोगी लेखन में ढालता है।",
      "demo.resultSeven": "पहले विचार लिखें, फिर Nospace उसे स्वाभाविक बना देगा।",
      "demo.resultEight": "इनपुट अधूरा हो तब भी Nospace वाक्य का प्रवाह बनाए रखता है।",
      "demo.editorText": "Nospace के साथ, गलतियाँ होने पर भी आपके विचार जल्दी स्वाभाविक वाक्यों में बदल जाते हैं।",
      "demo.editorStats": "पंक्ति: 1　अक्षर: 97　स्थिति: 97",
      "demo.select": "↑↓ चुनें",
      "demo.insert": "↵ डालें",
      "demo.close": "esc बंद करें",
      "process.title": "इनपुट को, <br><span>सोचने की गति दें।</span>",
      "process.lede": "लिखें। विकल्प चुनें। वाक्य उसी जगह लौटता है जहाँ आपने शुरुआत की थी। अतिरिक्त विंडो नहीं।",
      "process.input.label": "इनपुट",
      "process.input.title": "विचार जैसा आए,<br>वैसा लिखें।",
      "process.input.text": "टाइपो कोई समस्या नहीं। Nospace संदर्भ समझकर स्वाभाविक विकल्प बनाता है।",
      "process.input.example": "nospacekemadadsebhiaapkevicharsahajvakyabanjatehain",
      "process.reconstruct.label": "पुनर्निर्माण",
      "process.reconstruct.title": "AI पाँच<br>स्वाभाविक विकल्प बनाता है।",
      "process.reconstruct.text": "विकल्प संदर्भ के अनुसार आते हैं, इसलिए सही रूप खोजने में कम समय लगता है।",
      "process.reconstruct.example": "Nospace के साथ, गलतियाँ होने पर भी आपके विचार जल्दी स्वाभाविक वाक्यों में बदल जाते हैं।",
      "process.insert.label": "डालें",
      "process.insert.title": "वाक्य को अपने<br>ऐप में वापस डालें।",
      "process.insert.text": "शॉर्टकट से खोलें, परिणाम चुनें और उसी फ़ोकस स्थान पर लौटें।",
      "process.insert.app": "नोट्स",
      "process.insert.example": "Nospace के साथ, गलतियाँ होने पर भी आपके विचार जल्दी स्वाभाविक वाक्यों में बदल जाते हैं।",
      "pricing.eyebrow": "लागत / प्रति पांडुलिपि",
      "pricing.title": "पाँच डॉलर में,<br><span>लगभग 10,000 पृष्ठ।</span>",
      "pricing.lede": "Nospace का कोई उपयोग शुल्क नहीं है। यह अनुमान मापी गई लंबी पीढ़ी पर आधारित है।",
      "pricing.callout.title": "यह माप पर आधारित अनुमान है।",
      "pricing.callout.text": "मॉडल की कीमत, कैश और अनुबंध बदलने पर वास्तविक शुल्क भी बदलता है।",
      "pricing.ledger.unit": "लंबा जनरेशन / मापा गया",
      "pricing.ledger.estimate": "अनुमान / USD",
      "pricing.measure.title": "एक पांडुलिपि पृष्ठ",
      "pricing.measure.text": "1,238 जापानी अक्षर<br>आउटपुट / 400 अक्षर",
      "pricing.model.label": "मॉडल",
      "pricing.model.detail": "सिस्टम प्रॉम्प्ट शामिल",
      "pricing.provider.meta": "मापा गया उत्तर / एक कॉल",
      "pricing.provider.estimate": "प्रति कॉल अनुमान",
      "pricing.rate.input": "इनपुट",
      "pricing.rate.cachedInput": "कैश्ड इनपुट",
      "pricing.rate.cacheWrite": "कैश लेखन",
      "pricing.rate.output": "आउटपुट",
      "pricing.provider.link": "आधिकारिक कीमत देखें",
      "pricing.provider.linkLabel": "नई टैब में GPT-5.6 Luna की आधिकारिक कीमत देखें",
      "pricing.assumptions.label": "मापन",
      "pricing.assumptions.text": "हमने 3,981 अक्षरों के सिस्टम निर्देशों वाली Responses API रिक्वेस्ट मापी: 1,156 इनपुट tokens, 986 आउटपुट tokens और 1,238 आउटपुट अक्षर। 400 अक्षर प्रति पृष्ठ पर एक कॉल लगभग 3.1 पृष्ठ और पाँच डॉलर लगभग 3,400 कॉल या 10,000 पृष्ठ हैं।",
      "pricing.priceNote.label": "कीमत नोट",
      "pricing.priceNote.text": "शॉर्ट-कॉन्टेक्स्ट दरों पर मापी गई लागत प्रति कॉल $0.00147205 है।",
      "pricing.longContext.label": "कीमत में बदलाव",
      "pricing.longContext.text": "लंबे संदर्भ की दरें अलग हो सकती हैं। वास्तविक शुल्क के लिए आधिकारिक कीमत और अपने उपयोग की जाँच करें।",
      "privacy.title": "Nospace आपका डेटा<br><span>सहेजता नहीं है।</span>",
      "privacy.lede": "Nospace आपके चुने हुए API से सीधे बात करता है। कोई Nospace relay server नहीं है।",
      "privacy.card.label": "API गंतव्य",
      "privacy.card.title": "आपका पाठ जाता है<br><strong>चुने हुए API को।</strong>",
      "privacy.card.text": "Nospace सीधे OpenAI API या OpenRouter API का उपयोग करता है। आपका इनपुट और निर्देश चुने हुए API को जाते हैं, Nospace के सर्वर को नहीं।",
      "privacy.card.destination": "गंतव्य",
      "privacy.card.request": "API अनुरोध",
      "privacy.card.tag": "कोई Nospace relay server नहीं",
      "privacy.footnotes.keyTitle": "API कुंजी",
      "privacy.footnotes.keyText": "macOS Keychain में सुरक्षित।",
      "privacy.footnotes.permissionTitle": "अनुमति न होने पर",
      "privacy.footnotes.permissionText": "क्लिपबोर्ड से परिणाम को हाथ से पेस्ट करें।",
      "privacy.footnotes.storageTitle": "ऐप संग्रहण",
      "privacy.footnotes.storageText": "इनपुट और विकल्प डिस्क पर नहीं बचते।",
      "privacy.analytics.title": "वेबसाइट विश्लेषण",
      "privacy.analytics.text": "यह वेबसाइट Google Analytics का उपयोग करती है। सहमति देने पर Cookie से विज़िट का विश्लेषण होता है। असहमति पर भी सीमित Cookie-रहित जानकारी Google को भेजी जाती है।",
      "privacy.analytics.link": "Google जानकारी का उपयोग कैसे करता है",
      "privacy.analytics.linkLabel": "नई टैब में Google के जानकारी उपयोग को देखें",
      "privacy.analytics.privacyLink": "Google की गोपनीयता नीति",
      "privacy.analytics.privacyLinkLabel": "नई टैब में Google की गोपनीयता नीति देखें",
      "consent.title": "विश्लेषण सेटिंग्स",
      "consent.label": "विश्लेषण विकल्प",
      "consent.text": "सहमति देने पर Google Analytics Cookie का उपयोग करके विज़िट का विश्लेषण करता है। असहमति पर सीमित Cookie-रहित जानकारी Google को भेजी जाती है। आप बाद में चुनाव बदल सकते हैं।",
      "consent.details": "डेटा का उपयोग देखें",
      "consent.deny": "असहमति",
      "consent.grant": "सहमति",
      "consent.settings": "Cookie सेटिंग्स",
      "download.title": "अगली पंक्ति<br><span>अभी लिखें।</span>",
      "download.lede": "macOS 14 या बाद का संस्करण। अभी शुरू करें।",
      "download.linkLabel": "नई टैब में Nospace डाउनलोड करें",
      "download.socialLabel": "नवीनतम अपडेट",
      "download.socialText": "रिलीज़ और इस्तेमाल के नए तरीकों के लिए हमें फ़ॉलो करें।",
      "download.socialLink": "@nospace_app को फ़ॉलो करें",
      "download.socialAria": "नई टैब में Nospace के आधिकारिक X खाते को फ़ॉलो करें",
      "footer.tagline": "विचारों की गति से लिखें।",
      "footer.xAria": "नई टैब में Nospace का आधिकारिक X खाता खोलें"
    }),
    pt: locale({
      "meta.description": "Transforme entradas fonéticas e erros em texto natural com IA e insira o resultado escolhido no aplicativo que você já estava usando.",
      "document.title": "Nospace — Escreva no ritmo do pensamento.",
      "skip.main": "Pular para o conteúdo principal",
      "brand.homeLabel": "Ir para a página inicial do Nospace",
      "nav.label": "Navegação principal",
      "nav.flow": "Como funciona",
      "nav.cost": "Custo",
      "nav.privacy": "Dados e permissões",
      "nav.download": "Baixar",
      "hero.title": "<span class=\"hero__headline-line hero__headline-line--ink\">Escreva no ritmo</span><br><em>do pensamento.</em>",
      "hero.lede": "Digite sem travar por causa dos erros e deixe o Nospace transformar o rascunho em algo natural.",
      "hero.privacyLink": "Veja como os dados são tratados",
      "hero.note": "Seu texto vai para a API escolhida para gerar candidatos. A chave da API fica no Chaves do macOS.",
      "hero.shortcutLabel": "Abra o painel de entrada com Shift Space",
      "hero.openWith": "ABRIR COM",
      "hero.visualAria": "Demonstração do Nospace: digite texto fonético, revise candidatos naturais e insira o resultado escolhido",
      "hero.demoLanguage": "Português",
      "hero.demoMeta": "DEMONSTRAÇÃO",
      "hero.demoTogglePause": "Pausar o vídeo",
      "hero.demoTogglePlay": "Reproduzir o vídeo",
      "hero.demoPause": "PAUSAR",
      "hero.demoPlay": "REPRODUZIR",
      "hero.demoEditorSubtitle": "Editado",
      "hero.demoEditorMode": "Texto simples",
      "hero.demoEditorStatus": "Linha: 1　Caracteres: 0　Posição: 0",
      "hero.demoPanelSettings": "Configurações da demonstração",
      "hero.demoPanelInputPlaceholder": "Digite foneticamente…",
      "hero.demoPanelLanguageEnglish": "English",
      "hero.demoPanelLanguageTarget": "Português",
      "hero.demoPanelConvert": "Gerar",
      "hero.demoPanelShortcuts": "↵ Nova linha",
      "hero.demoPanelLoading": "Reconstruindo texto natural",
      "hero.demoPanelCancel": "Cancelar",
      "hero.demoPanelCandidateCount": "{count} candidatos",
      "hero.demoPanelCandidateCountOne": "{count} candidato",
      "hero.demoPanelAdjust": "Ajustar",
      "hero.demoPanelRegenerate": "Gerar novamente",
      "hero.demoPanelAddDictionary": "Adicionar ao dicionário",
      "hero.demoPanelEdit": "Editar　↪",
      "hero.demoPanelTranslate": "Traduzir ⌘T",
      "hero.demoPanelSelect": "↑↓ Selecionar",
      "hero.demoPanelInsert": "↵ Inserir",
      "hero.demoPanelClose": "esc Fechar",
      "hero.sr": "Uma demonstração sem áudio mostra a entrada fonética virando candidatos naturais e o resultado escolhido voltando ao aplicativo em foco.",
      "hero.visualFootInput": "Digite a versão aproximada",
      "hero.visualFootSelect": "Escolha um candidato",
      "eyebrow.howItFlows": "COMO FUNCIONA",
      "eyebrow.plainOnPurpose": "CLARO DE PROPÓSITO",
      "eyebrow.startTyping": "COMECE A DIGITAR",
      "eyebrow.websiteAnalytics": "ANÁLISE DO SITE",
      "demo.input": "ENTRADA",
      "demo.rawInput": "comnospaceatecomerrostuasideiasviramfrasesnaturais",
      "demo.resultOne": "Com o Nospace, até com erros de digitação, suas ideias viram frases naturais rapidamente.",
      "demo.resultTwo": "Com o Nospace, erros de digitação viram texto natural em segundos.",
      "demo.resultThree": "O Nospace transforma pensamentos soltos em texto claro e natural.",
      "demo.resultFour": "Até uma entrada imperfeita pode virar uma frase pronta.",
      "demo.resultFive": "Com o Nospace, uma entrada rápida vira uma frase natural.",
      "demo.resultSix": "O Nospace organiza ideias escritas às pressas em texto pronto para usar.",
      "demo.resultSeven": "Escreva a ideia primeiro e deixe o Nospace dar o acabamento natural.",
      "demo.resultEight": "Mesmo com lacunas, o Nospace mantém o sentido da frase.",
      "demo.editorText": "Com o Nospace, até com erros de digitação, suas ideias viram frases naturais rapidamente.",
      "demo.editorStats": "Linha: 1　Caracteres: 97　Posição: 97",
      "demo.select": "↑↓ Selecionar",
      "demo.insert": "↵ Inserir",
      "demo.close": "esc Fechar",
      "process.title": "Escreva no ritmo,<br><span>do pensamento.</span>",
      "process.lede": "Digite. Escolha um candidato. A frase volta ao lugar onde você começou, sem outra janela para percorrer.",
      "process.input.label": "ENTRADA",
      "process.input.title": "Digite a ideia<br>como ela vier.",
      "process.input.text": "Erros não são problema. O Nospace entende o contexto e cria candidatos naturais.",
      "process.input.example": "comnospaceatecomerrostuasideiasviramfrasesnaturais",
      "process.reconstruct.label": "RECONSTRUIR",
      "process.reconstruct.title": "A IA cria cinco<br>opções naturais.",
      "process.reconstruct.text": "Os candidatos seguem o contexto, então você passa menos tempo procurando a conversão certa.",
      "process.reconstruct.example": "Com o Nospace, até com erros de digitação, suas ideias viram frases naturais rapidamente.",
      "process.insert.label": "INSERIR",
      "process.insert.title": "Coloque a frase<br>de volta no app.",
      "process.insert.text": "Abra com um atalho, escolha um resultado e volte à posição que estava em foco.",
      "process.insert.app": "Notas",
      "process.insert.example": "Com o Nospace, até com erros de digitação, suas ideias viram frases naturais rapidamente.",
      "pricing.eyebrow": "CUSTO / POR MANUSCRITO",
      "pricing.title": "Cinco dólares,<br><span>cerca de 10 mil páginas.</span>",
      "pricing.lede": "O Nospace não cobra pelo uso. Esta estimativa parte de uma geração longa medida para mostrar o que cinco dólares cobrem.",
      "pricing.callout.title": "É uma estimativa medida.",
      "pricing.callout.text": "O valor real muda com preços do modelo, cache e condições contratuais.",
      "pricing.ledger.unit": "GERAÇÃO LONGA / MEDIDA",
      "pricing.ledger.estimate": "ESTIMATIVA / USD",
      "pricing.measure.title": "Uma página de manuscrito",
      "pricing.measure.text": "1.238 caracteres japoneses<br>SAÍDA / 400 caracteres",
      "pricing.model.label": "MODELO",
      "pricing.model.detail": "prompt do sistema incluído",
      "pricing.provider.meta": "resposta medida / uma chamada",
      "pricing.provider.estimate": "estimado por chamada",
      "pricing.rate.input": "ENTRADA",
      "pricing.rate.cachedInput": "ENTRADA EM CACHE",
      "pricing.rate.cacheWrite": "GRAVAÇÃO EM CACHE",
      "pricing.rate.output": "SAÍDA",
      "pricing.provider.link": "Ver preços oficiais",
      "pricing.provider.linkLabel": "Ver os preços oficiais do GPT-5.6 Luna em uma nova aba",
      "pricing.assumptions.label": "MEDIÇÃO",
      "pricing.assumptions.text": "Medimos uma solicitação da Responses API com 3.981 caracteres de instruções do sistema: 1.156 tokens de entrada, 986 de saída e 1.238 caracteres de saída. A 400 caracteres por página, uma chamada equivale a cerca de 3,1 páginas e cinco dólares a cerca de 3.400 chamadas ou 10 mil páginas.",
      "pricing.priceNote.label": "NOTA DE PREÇO",
      "pricing.priceNote.text": "Com as tarifas de contexto curto, o custo medido é de $0.00147205 por chamada.",
      "pricing.longContext.label": "MUDANÇAS DE PREÇO",
      "pricing.longContext.text": "As tarifas de contexto longo podem mudar. Confira os preços oficiais e seu uso para saber o valor real.",
      "privacy.title": "O Nospace não<br><span>guarda seus dados.</span>",
      "privacy.lede": "O Nospace fala diretamente com a API escolhida. Não existe servidor intermediário do Nospace.",
      "privacy.card.label": "DESTINO DA API",
      "privacy.card.title": "Seu texto vai<br><strong>para a API escolhida.</strong>",
      "privacy.card.text": "O Nospace usa diretamente a API da OpenAI ou da OpenRouter. Sua entrada e as instruções de reconstrução vão para a API selecionada, não para um servidor do Nospace ou outro destino.",
      "privacy.card.destination": "Destino",
      "privacy.card.request": "Solicitação da API",
      "privacy.card.tag": "Sem servidor intermediário do Nospace",
      "privacy.footnotes.keyTitle": "Chave da API",
      "privacy.footnotes.keyText": "Guardada no Chaves do macOS.",
      "privacy.footnotes.permissionTitle": "Sem permissão",
      "privacy.footnotes.permissionText": "Cole manualmente o resultado da área de transferência.",
      "privacy.footnotes.storageTitle": "Armazenamento do app",
      "privacy.footnotes.storageText": "A entrada e os candidatos não são salvos no disco.",
      "privacy.analytics.title": "Análise do site",
      "privacy.analytics.text": "Este site usa o Google Analytics. Se você aceitar, cookies ajudam a analisar as visitas. Se recusar, informações limitadas sem cookies ainda são enviadas ao Google.",
      "privacy.analytics.link": "Como o Google usa informações",
      "privacy.analytics.linkLabel": "Veja como o Google usa informações em uma nova aba",
      "privacy.analytics.privacyLink": "Política de privacidade do Google",
      "privacy.analytics.privacyLinkLabel": "Veja a política de privacidade do Google em uma nova aba",
      "consent.title": "Configurações de análise",
      "consent.label": "ESCOLHA DE ANÁLISE",
      "consent.text": "Se você aceitar, o Google Analytics usa cookies para analisar as visitas. Se recusar, informações limitadas sem cookies ainda são enviadas ao Google. Você pode mudar a escolha depois.",
      "consent.details": "Veja como os dados são tratados",
      "consent.deny": "Recusar",
      "consent.grant": "Aceitar",
      "consent.settings": "Configurações de cookies",
      "download.title": "Escreva a próxima frase<br><span>agora mesmo.</span>",
      "download.lede": "macOS 14 ou posterior. Comece em instantes.",
      "download.linkLabel": "Baixar o Nospace em uma nova aba",
      "download.socialLabel": "NOVIDADES",
      "download.socialText": "Acompanhe lançamentos e novas formas de usar o Nospace.",
      "download.socialLink": "Siga @nospace_app",
      "download.socialAria": "Siga a conta oficial do Nospace no X em uma nova aba",
      "footer.tagline": "Escreva no ritmo do pensamento.",
      "footer.xAria": "Abra a conta oficial do Nospace no X em uma nova aba"
    }),
    fr: locale({
      "meta.description": "Transformez une saisie phonétique et des fautes en texte naturel avec l’IA, puis insérez le résultat choisi dans l’application déjà ouverte.",
      "document.title": "Nospace — Écrivez au rythme de vos idées.",
      "skip.main": "Aller au contenu principal",
      "brand.homeLabel": "Accéder à l’accueil de Nospace",
      "nav.label": "Navigation principale",
      "nav.flow": "Fonctionnement",
      "nav.cost": "Coût",
      "nav.privacy": "Données et autorisations",
      "nav.download": "Télécharger",
      "hero.title": "<span class=\"hero__headline-line hero__headline-line--ink\">Écrivez au rythme</span><br><em>de vos idées.</em>",
      "hero.lede": "Écrivez sans vous arrêter pour corriger les fautes et laissez Nospace rendre le brouillon naturel.",
      "hero.privacyLink": "Voir comment les données sont traitées",
      "hero.note": "Votre texte est envoyé à l’API choisie pour générer des propositions. La clé API reste dans le trousseau macOS.",
      "hero.shortcutLabel": "Ouvrir le panneau de saisie avec Maj Espace",
      "hero.openWith": "OUVRIR AVEC",
      "hero.visualAria": "Démonstration de Nospace : saisissez du texte phonétique, consultez des propositions naturelles et insérez le résultat choisi",
      "hero.demoLanguage": "Français",
      "hero.demoMeta": "DÉMONSTRATION",
      "hero.demoTogglePause": "Mettre la vidéo en pause",
      "hero.demoTogglePlay": "Lire la vidéo",
      "hero.demoPause": "PAUSE",
      "hero.demoPlay": "LIRE",
      "hero.demoEditorSubtitle": "Modifié",
      "hero.demoEditorMode": "Texte brut",
      "hero.demoEditorStatus": "Ligne : 1　Caractères : 0　Position : 0",
      "hero.demoPanelSettings": "Réglages de la démonstration",
      "hero.demoPanelInputPlaceholder": "Saisissez phonétiquement…",
      "hero.demoPanelLanguageEnglish": "English",
      "hero.demoPanelLanguageTarget": "Français",
      "hero.demoPanelConvert": "Générer",
      "hero.demoPanelShortcuts": "↵ Nouvelle ligne",
      "hero.demoPanelLoading": "Reconstruction du texte naturel",
      "hero.demoPanelCancel": "Annuler",
      "hero.demoPanelCandidateCount": "{count} propositions",
      "hero.demoPanelCandidateCountOne": "{count} proposition",
      "hero.demoPanelAdjust": "Ajuster",
      "hero.demoPanelRegenerate": "Régénérer",
      "hero.demoPanelAddDictionary": "Ajouter au dictionnaire",
      "hero.demoPanelEdit": "Modifier　↪",
      "hero.demoPanelTranslate": "Traduire ⌘T",
      "hero.demoPanelSelect": "↑↓ Sélectionner",
      "hero.demoPanelInsert": "↵ Insérer",
      "hero.demoPanelClose": "esc Fermer",
      "hero.sr": "Une démonstration silencieuse montre comment une saisie phonétique devient des propositions naturelles, puis comment le résultat choisi revient dans l’application active.",
      "hero.visualFootInput": "Saisissez la version approximative",
      "hero.visualFootSelect": "Choisissez une proposition",
      "eyebrow.howItFlows": "COMMENT ÇA MARCHE",
      "eyebrow.plainOnPurpose": "SIMPLEMENT, À DESSEIN",
      "eyebrow.startTyping": "COMMENCEZ À ÉCRIRE",
      "eyebrow.websiteAnalytics": "ANALYSE DU SITE",
      "demo.input": "SAISIE",
      "demo.rawInput": "avecnospacememeavecdesfautesvosideesdeviennentnaturelles",
      "demo.resultOne": "Avec Nospace, même avec des fautes, vos idées deviennent rapidement des phrases naturelles.",
      "demo.resultTwo": "Avec Nospace, les fautes deviennent du texte naturel en quelques secondes.",
      "demo.resultThree": "Nospace transforme les idées brutes en texte clair et naturel.",
      "demo.resultFour": "Même une saisie imparfaite peut devenir une phrase aboutie.",
      "demo.resultFive": "Avec Nospace, une saisie rapide devient une phrase naturelle.",
      "demo.resultSix": "Nospace organise vos idées écrites à la volée en texte prêt à l’emploi.",
      "demo.resultSeven": "Écrivez d’abord l’idée et laissez Nospace lui donner un ton naturel.",
      "demo.resultEight": "Même si la saisie est incomplète, Nospace garde le fil de la phrase.",
      "demo.editorText": "Avec Nospace, même avec des fautes, vos idées deviennent rapidement des phrases naturelles.",
      "demo.editorStats": "Ligne : 1　Caractères : 96　Position : 96",
      "demo.select": "↑↓ Sélectionner",
      "demo.insert": "↵ Insérer",
      "demo.close": "esc Fermer",
      "process.title": "Écrivez au rythme,<br><span>de vos idées.</span>",
      "process.lede": "Écrivez. Choisissez une proposition. La phrase revient là où vous avez commencé, sans fenêtre supplémentaire.",
      "process.input.label": "SAISIE",
      "process.input.title": "Saisissez l’idée<br>comme elle vient.",
      "process.input.text": "Les fautes sont permises. Nospace comprend le contexte et crée des propositions naturelles.",
      "process.input.example": "avecnospacememeavecdesfautesvosideesdeviennentnaturelles",
      "process.reconstruct.label": "RECONSTRUCTION",
      "process.reconstruct.title": "L’IA crée cinq<br>options naturelles.",
      "process.reconstruct.text": "Les propositions suivent le contexte : vous passez moins de temps à chercher la bonne conversion.",
      "process.reconstruct.example": "Avec Nospace, même avec des fautes, vos idées deviennent rapidement des phrases naturelles.",
      "process.insert.label": "INSERTION",
      "process.insert.title": "Remettez la phrase<br>dans votre application.",
      "process.insert.text": "Ouvrez avec un raccourci, choisissez un résultat et revenez à la position qui avait le focus.",
      "process.insert.app": "Notes",
      "process.insert.example": "Avec Nospace, même avec des fautes, vos idées deviennent rapidement des phrases naturelles.",
      "pricing.eyebrow": "COÛT / PAR MANUSCRIT",
      "pricing.title": "Cinq dollars,<br><span>environ 10 000 pages.</span>",
      "pricing.lede": "Nospace ne facture pas son utilisation. Cette estimation part d’une génération longue mesurée pour montrer ce que couvrent cinq dollars.",
      "pricing.callout.title": "Une estimation fondée sur une mesure.",
      "pricing.callout.text": "Le montant réel varie selon le prix du modèle, le cache et les conditions du contrat.",
      "pricing.ledger.unit": "GÉNÉRATION LONGUE / MESURÉE",
      "pricing.ledger.estimate": "ESTIMATION / USD",
      "pricing.measure.title": "Une page de manuscrit",
      "pricing.measure.text": "1 238 caractères japonais<br>SORTIE / 400 caractères",
      "pricing.model.label": "MODÈLE",
      "pricing.model.detail": "prompt système inclus",
      "pricing.provider.meta": "réponse mesurée / un appel",
      "pricing.provider.estimate": "estimation par appel",
      "pricing.rate.input": "ENTRÉE",
      "pricing.rate.cachedInput": "ENTRÉE EN CACHE",
      "pricing.rate.cacheWrite": "ÉCRITURE DU CACHE",
      "pricing.rate.output": "SORTIE",
      "pricing.provider.link": "Voir les tarifs officiels",
      "pricing.provider.linkLabel": "Voir les tarifs officiels de GPT-5.6 Luna dans un nouvel onglet",
      "pricing.assumptions.label": "MESURE",
      "pricing.assumptions.text": "Nous avons mesuré une requête Responses API contenant 3 981 caractères d’instructions système : 1 156 tokens en entrée, 986 en sortie et 1 238 caractères en sortie. À 400 caractères par page, un appel représente environ 3,1 pages et cinq dollars environ 3 400 appels ou 10 000 pages.",
      "pricing.priceNote.label": "NOTE DE PRIX",
      "pricing.priceNote.text": "Avec les tarifs de contexte court, le coût mesuré est de $0.00147205 par appel.",
      "pricing.longContext.label": "ÉVOLUTION DES PRIX",
      "pricing.longContext.text": "Les tarifs de contexte long peuvent différer. Consultez les tarifs officiels et votre utilisation pour connaître le montant réel.",
      "privacy.title": "Nospace ne<br><span>conserve pas vos données.</span>",
      "privacy.lede": "Nospace échange directement avec l’API que vous choisissez. Aucun serveur relais Nospace.",
      "privacy.card.label": "DESTINATION DE L’API",
      "privacy.card.title": "Votre texte va<br><strong>à l’API choisie.</strong>",
      "privacy.card.text": "Nospace utilise directement l’API OpenAI ou OpenRouter. Votre saisie et les instructions de reconstruction vont à l’API sélectionnée, pas à un serveur Nospace ni à une autre destination.",
      "privacy.card.destination": "Destination",
      "privacy.card.request": "Requête API",
      "privacy.card.tag": "Aucun serveur relais Nospace",
      "privacy.footnotes.keyTitle": "Clé API",
      "privacy.footnotes.keyText": "Stockée dans le trousseau macOS.",
      "privacy.footnotes.permissionTitle": "Sans autorisation",
      "privacy.footnotes.permissionText": "Collez manuellement le résultat depuis le presse-papiers.",
      "privacy.footnotes.storageTitle": "Stockage de l’app",
      "privacy.footnotes.storageText": "La saisie et les propositions ne sont pas enregistrées sur le disque.",
      "privacy.analytics.title": "Analyse du site web",
      "privacy.analytics.text": "Ce site utilise Google Analytics. Si vous acceptez, les cookies servent à analyser les visites. Si vous refusez, des informations limitées sans cookies sont tout de même envoyées à Google.",
      "privacy.analytics.link": "Comment Google utilise les informations",
      "privacy.analytics.linkLabel": "Voir comment Google utilise les informations dans un nouvel onglet",
      "privacy.analytics.privacyLink": "Règles de confidentialité Google",
      "privacy.analytics.privacyLinkLabel": "Voir les règles de confidentialité Google dans un nouvel onglet",
      "consent.title": "Réglages de l’analyse",
      "consent.label": "CHOIX D’ANALYSE",
      "consent.text": "Si vous acceptez, Google Analytics utilise des cookies pour analyser les visites. Si vous refusez, des informations limitées sans cookies sont tout de même envoyées à Google. Vous pouvez modifier ce choix plus tard.",
      "consent.details": "Voir comment les données sont traitées",
      "consent.deny": "Refuser",
      "consent.grant": "Accepter",
      "consent.settings": "Réglages des cookies",
      "download.title": "Écrivez la prochaine phrase<br><span>dès maintenant.</span>",
      "download.lede": "macOS 14 ou version ultérieure. Commencez en quelques secondes.",
      "download.linkLabel": "Télécharger Nospace dans un nouvel onglet",
      "download.socialLabel": "DERNIÈRES NOUVELLES",
      "download.socialText": "Suivez les sorties et les nouvelles façons d’utiliser Nospace.",
      "download.socialLink": "Suivre @nospace_app",
      "download.socialAria": "Suivre le compte X officiel de Nospace dans un nouvel onglet",
      "footer.tagline": "Écrivez au rythme de vos idées.",
      "footer.xAria": "Ouvrir le compte X officiel de Nospace dans un nouvel onglet"
    }),
    it: locale({
      "meta.description": "Trasforma input fonetico e refusi in testo naturale con l’AI, poi inserisci il risultato scelto nell’app che stavi già usando.",
      "document.title": "Nospace — Scrivi al ritmo dei tuoi pensieri.",
      "skip.main": "Vai al contenuto principale",
      "brand.homeLabel": "Vai alla home page di Nospace",
      "nav.label": "Navigazione principale",
      "nav.flow": "Come funziona",
      "nav.cost": "Costo",
      "nav.privacy": "Dati e permessi",
      "nav.download": "Scarica",
      "hero.title": "<span class=\"hero__headline-line hero__headline-line--ink\">Scrivi al ritmo</span><br><em>dei tuoi pensieri.</em>",
      "hero.lede": "Scrivi senza fermarti per gli errori e lascia che Nospace trasformi la bozza in qualcosa di naturale.",
      "hero.privacyLink": "Scopri come vengono gestiti i dati",
      "hero.note": "Il testo viene inviato all’API che scegli per generare le proposte. La chiave API resta nel Portachiavi di macOS.",
      "hero.shortcutLabel": "Apri il pannello di input con Shift Space",
      "hero.openWith": "APRI CON",
      "hero.visualAria": "Demo di Nospace: scrivi testo fonetico, esamina proposte naturali e inserisci il risultato scelto",
      "hero.demoLanguage": "Italiano",
      "hero.demoMeta": "DEMO DEL PRODOTTO",
      "hero.demoTogglePause": "Metti in pausa il video",
      "hero.demoTogglePlay": "Riproduci il video",
      "hero.demoPause": "PAUSA",
      "hero.demoPlay": "RIPRODUCI",
      "hero.demoEditorSubtitle": "Modificato",
      "hero.demoEditorMode": "Testo semplice",
      "hero.demoEditorStatus": "Riga: 1　Caratteri: 0　Posizione: 0",
      "hero.demoPanelSettings": "Impostazioni della demo",
      "hero.demoPanelInputPlaceholder": "Scrivi foneticamente…",
      "hero.demoPanelLanguageEnglish": "English",
      "hero.demoPanelLanguageTarget": "Italiano",
      "hero.demoPanelConvert": "Genera",
      "hero.demoPanelShortcuts": "↵ Nuova riga",
      "hero.demoPanelLoading": "Ricostruzione del testo naturale",
      "hero.demoPanelCancel": "Annulla",
      "hero.demoPanelCandidateCount": "{count} proposte",
      "hero.demoPanelCandidateCountOne": "{count} proposta",
      "hero.demoPanelAdjust": "Regola",
      "hero.demoPanelRegenerate": "Rigenera",
      "hero.demoPanelAddDictionary": "Aggiungi al dizionario",
      "hero.demoPanelEdit": "Modifica　↪",
      "hero.demoPanelTranslate": "Traduci ⌘T",
      "hero.demoPanelSelect": "↑↓ Seleziona",
      "hero.demoPanelInsert": "↵ Inserisci",
      "hero.demoPanelClose": "esc Chiudi",
      "hero.sr": "Una demo senza audio mostra come l’input fonetico diventa una proposta naturale e come il risultato scelto torna nell’app attiva.",
      "hero.visualFootInput": "Scrivi la versione approssimativa",
      "hero.visualFootSelect": "Scegli una proposta",
      "eyebrow.howItFlows": "COME FUNZIONA",
      "eyebrow.plainOnPurpose": "CHIARO, DI PROPOSITO",
      "eyebrow.startTyping": "INIZIA A SCRIVERE",
      "eyebrow.websiteAnalytics": "ANALISI DEL SITO",
      "demo.input": "INPUT",
      "demo.rawInput": "connospaceancheconerroriletueideediventanofrasinaturali",
      "demo.resultOne": "Con Nospace, anche con gli errori, le tue idee diventano rapidamente frasi naturali.",
      "demo.resultTwo": "Con Nospace, anche i refusi diventano testo naturale in pochi secondi.",
      "demo.resultThree": "Nospace trasforma i pensieri grezzi in testo chiaro e naturale.",
      "demo.resultFour": "Anche un input imperfetto può diventare una frase completa.",
      "demo.resultFive": "Con Nospace, anche un input rapido diventa una frase naturale.",
      "demo.resultSix": "Nospace organizza i pensieri scritti di fretta in un testo pronto da usare.",
      "demo.resultSeven": "Scrivi prima l’idea e lascia che Nospace le dia un tono naturale.",
      "demo.resultEight": "Anche con un input incompleto, Nospace mantiene il filo della frase.",
      "demo.editorText": "Con Nospace, anche con gli errori, le tue idee diventano rapidamente frasi naturali.",
      "demo.editorStats": "Riga: 1　Caratteri: 96　Posizione: 96",
      "demo.select": "↑↓ Seleziona",
      "demo.insert": "↵ Inserisci",
      "demo.close": "esc Chiudi",
      "process.title": "Scrivi al ritmo,<br><span>dei tuoi pensieri.</span>",
      "process.lede": "Scrivi. Scegli una proposta. La frase torna al punto da cui sei partito, senza finestre extra.",
      "process.input.label": "INPUT",
      "process.input.title": "Scrivi il pensiero<br>così come arriva.",
      "process.input.text": "Gli errori vanno bene. Nospace capisce il contesto e crea proposte naturali.",
      "process.input.example": "connospaceancheconerroriletueideediventanofrasinaturali",
      "process.reconstruct.label": "RICOSTRUZIONE",
      "process.reconstruct.title": "L’AI crea cinque<br>opzioni naturali.",
      "process.reconstruct.text": "Le proposte seguono il contesto, così passi meno tempo a cercare la conversione giusta.",
      "process.reconstruct.example": "Con Nospace, anche con gli errori, le tue idee diventano rapidamente frasi naturali.",
      "process.insert.label": "INSERISCI",
      "process.insert.title": "Riporta la frase<br>nella tua app.",
      "process.insert.text": "Apri con una scorciatoia, scegli il risultato e torna alla posizione che aveva il focus.",
      "process.insert.app": "Note",
      "process.insert.example": "Con Nospace, anche con gli errori, le tue idee diventano rapidamente frasi naturali.",
      "pricing.eyebrow": "COSTO / PER MANOSCRITTO",
      "pricing.title": "Cinque dollari,<br><span>circa 10.000 pagine.</span>",
      "pricing.lede": "Nospace non applica costi d’uso. Questa stima parte da una generazione lunga misurata per mostrare cosa coprono cinque dollari.",
      "pricing.callout.title": "È una stima misurata.",
      "pricing.callout.text": "L’importo reale cambia con i prezzi del modello, la cache e le condizioni contrattuali.",
      "pricing.ledger.unit": "GENERAZIONE LUNGA / MISURATA",
      "pricing.ledger.estimate": "STIMA / USD",
      "pricing.measure.title": "Una pagina di manoscritto",
      "pricing.measure.text": "1.238 caratteri giapponesi<br>OUTPUT / 400 caratteri",
      "pricing.model.label": "MODELLO",
      "pricing.model.detail": "prompt di sistema incluso",
      "pricing.provider.meta": "risposta misurata / una chiamata",
      "pricing.provider.estimate": "stima per chiamata",
      "pricing.rate.input": "INPUT",
      "pricing.rate.cachedInput": "INPUT IN CACHE",
      "pricing.rate.cacheWrite": "SCRITTURA CACHE",
      "pricing.rate.output": "OUTPUT",
      "pricing.provider.link": "Vedi i prezzi ufficiali",
      "pricing.provider.linkLabel": "Vedi i prezzi ufficiali di GPT-5.6 Luna in una nuova scheda",
      "pricing.assumptions.label": "MISURAZIONE",
      "pricing.assumptions.text": "Abbiamo misurato una richiesta Responses API con 3.981 caratteri di istruzioni di sistema: 1.156 token in input, 986 in output e 1.238 caratteri in output. A 400 caratteri per pagina, una chiamata vale circa 3,1 pagine e cinque dollari circa 3.400 chiamate o 10.000 pagine.",
      "pricing.priceNote.label": "NOTA SUL PREZZO",
      "pricing.priceNote.text": "Con le tariffe per contesto breve, il costo misurato è $0.00147205 per chiamata.",
      "pricing.longContext.label": "CAMBIAMENTI DI PREZZO",
      "pricing.longContext.text": "Le tariffe per contesti lunghi possono differire. Controlla i prezzi ufficiali e il tuo utilizzo per conoscere l’importo reale.",
      "privacy.title": "Nospace non<br><span>conserva i tuoi dati.</span>",
      "privacy.lede": "Nospace comunica direttamente con l’API che scegli. Non esiste un server relay di Nospace.",
      "privacy.card.label": "DESTINAZIONE API",
      "privacy.card.title": "Il tuo testo va<br><strong>all’API scelta.</strong>",
      "privacy.card.text": "Nospace usa direttamente l’API OpenAI o OpenRouter. Il tuo input e le istruzioni di ricostruzione vanno all’API selezionata, non a un server Nospace o a un’altra destinazione.",
      "privacy.card.destination": "Destinazione",
      "privacy.card.request": "Richiesta API",
      "privacy.card.tag": "Nessun server relay di Nospace",
      "privacy.footnotes.keyTitle": "Chiave API",
      "privacy.footnotes.keyText": "Salvata nel Portachiavi di macOS.",
      "privacy.footnotes.permissionTitle": "Senza permesso",
      "privacy.footnotes.permissionText": "Incolla manualmente il risultato dagli appunti.",
      "privacy.footnotes.storageTitle": "Archiviazione dell’app",
      "privacy.footnotes.storageText": "Input e proposte non vengono salvati sul disco.",
      "privacy.analytics.title": "Analisi del sito",
      "privacy.analytics.text": "Questo sito usa Google Analytics. Se accetti, i cookie aiutano ad analizzare le visite. Se rifiuti, a Google vengono comunque inviate informazioni limitate senza cookie.",
      "privacy.analytics.link": "Come Google usa le informazioni",
      "privacy.analytics.linkLabel": "Vedi come Google usa le informazioni in una nuova scheda",
      "privacy.analytics.privacyLink": "Norme sulla privacy di Google",
      "privacy.analytics.privacyLinkLabel": "Vedi le norme sulla privacy di Google in una nuova scheda",
      "consent.title": "Impostazioni analisi",
      "consent.label": "SCELTA ANALISI",
      "consent.text": "Se accetti, Google Analytics usa i cookie per analizzare le visite. Se rifiuti, a Google vengono comunque inviate informazioni limitate senza cookie. Puoi cambiare questa scelta in seguito.",
      "consent.details": "Vedi come vengono gestiti i dati",
      "consent.deny": "Rifiuta",
      "consent.grant": "Accetta",
      "consent.settings": "Impostazioni cookie",
      "download.title": "Scrivi la prossima frase<br><span>subito.</span>",
      "download.lede": "macOS 14 o successivo. Inizia in un attimo.",
      "download.linkLabel": "Scarica Nospace in una nuova scheda",
      "download.socialLabel": "ULTIMI AGGIORNAMENTI",
      "download.socialText": "Segui le novità sui rilasci e sui modi di usare Nospace.",
      "download.socialLink": "Segui @nospace_app",
      "download.socialAria": "Segui l’account X ufficiale di Nospace in una nuova scheda",
      "footer.tagline": "Scrivi al ritmo dei tuoi pensieri.",
      "footer.xAria": "Apri l’account X ufficiale di Nospace in una nuova scheda"
    })
  };

  const normalizeLocale = (tag) => {
    if (typeof tag !== "string") {
      return null;
    }

    const normalized = tag.trim().replace(/_/g, "-").toLowerCase();
    if (!normalized) {
      return null;
    }
    if (normalized === "ja" || normalized.startsWith("ja-")) {
      return "ja";
    }
    if (normalized === "en" || normalized.startsWith("en-")) {
      return "en";
    }
    if (normalized === "zh" || normalized.startsWith("zh-")) {
      return /hant|tw|hk|mo/.test(normalized) ? "zh-Hant" : "zh-Hans";
    }
    if (normalized === "es" || normalized.startsWith("es-")) {
      return "es";
    }
    if (normalized === "hi" || normalized.startsWith("hi-")) {
      return "hi";
    }
    if (normalized === "pt" || normalized.startsWith("pt-")) {
      return "pt";
    }
    if (normalized === "fr" || normalized.startsWith("fr-")) {
      return "fr";
    }
    if (normalized === "it" || normalized.startsWith("it-")) {
      return "it";
    }
    return null;
  };

  const resolveLocale = (preferences) => {
    if (!Array.isArray(preferences) || preferences.length === 0) {
      return "ja";
    }

    for (const preference of preferences) {
      const resolved = normalizeLocale(preference);
      if (resolved) {
        return resolved;
      }
    }

    return "en";
  };

  window.NospaceLocalization = {
    supportedLocales,
    translations,
    normalizeLocale,
    resolveLocale
  };
})();
